name: Instagram Hunter

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Bot Token'
        required: true
      chat_id:
        description: 'Telegram ID'
        required: true

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Start Hunting
        env:
          BOT_TOKEN: ${{ github.event.inputs.token }}
          CHAT_ID: ${{ github.event.inputs.chat_id }}
        run: python hunter.py
